ProjetoJovemProgramadorMVC/Models/Aluno.cs
namespace ProjetoJovemProgramadorMVC.Models
{
    public class Aluno
    {
        public int Id { get; set; }
        public string Matricula { get; set; }
        public string Nome { get; set; }
        public string Cpf { get; set; }
        public int Idade { get; set; }
    }
}

ProjetoJovemProgramadorMVC/Models/ErrorViewModel.cs
namespace ProjetoJovemProgramadorMVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ProjetoJovemProgramadorMVC/Controllers/AlunoController.cs
using Microsoft.AspNetCore.Mvc;
using ProjetoJovemProgramadorMVC.Date.Repositorio.Interfaceer;
using ProjetoJovemProgramadorMVC.Models;

namespace ProjetoJovemProgramadorMVC.Controllers
{
    public class AlunoController : Controller
    {
        private readonly IAlunoRepositorio _alunoRepositorio;
        public AlunoController(IAlunoRepositorio alunoRepositorio)
        {
            _alunoRepositorio = alunoRepositorio;
        }
        public IActionResult Index()
        {
            var aluno = _alunoRepositorio.BuscarAlunos();
            return View(aluno);
        }

        //criando uma ação para o botão ADICIONAR ALUNO já criado no index
        public IActionResult AdicionarAluno()
        {
            return View();
        }

        public IActionResult InserirAluno(Aluno aluno) // classe Aluno e obejeto que referencia a classe aluno.
        {
            //
            try
            {
                _alunoRepositorio.InserirAlunos(aluno);
            }
            catch (Exception ex)
            {
                //ex.Error(ex, "Ocorreu um erro ao processar a requisição.");
                //ModelState.AddModelError(string.Empty, "Ocorreu um erro inesperado. Por favor, tente novamente mais tarde.");
            }

            return RedirectToAction("Index");
        }


    }
}

ProjetoJovemProgramadorMVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using ProjetoJovemProgramadorMVC.Models;
using System.Diagnostics;

namespace ProjetoJovemProgramadorMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ProjetoJovemProgramadorMVC/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;

namespace ProjetoJovemProgramadorMVC.Controllers
{
    public class LoginController : Controller
    {

        public IActionResult Index()
        {
            return View();
        }

        //[HttpPost]
        //public async Task<IActionResult> Logar(string username, string senha)
        //{
            
        //    return Json(new { });
        //}
    }
}

ProjetoJovemProgramadorMVC/Views/Aluno/AdicionarAluno.cshtml
@model Aluno


<form asp-controller="Aluno" asp-action="InserirAluno" method="post">
    @* caminho para onde o formulario deve ir *@

    <div class="form-container">
        <h2>Cadastro de Aluno</h2>
        <form>
            <div class="form-group">
                <label for="matricula">Matrícula</label>
                <input type="text" asp-for="Matricula" nid="matricula" name="matricula" required>
            </div>
            <div class="form-group">
                <label for="nome">Nome</label>
                <input type="text" asp-for="Nome" id="nome" name="nome" required>
            </div>
            <div class="form-group">
                <label for="cpf">CPF</label>
                <input type="text" asp-for="Cpf" id="cpf" name="cpf" required>
            </div>
            <div class="form-group">
                <label for="idade">Idade</label>
                <input type="number" asp-for="Idade" id="idade" name="idade" required>
            </div>
            <div class="btn-enviar">
                <button type="submit">Enviar</button>
            </div>
        </form>
    </div>
</form>

ProjetoJovemProgramadorMVC/Views/Aluno/Index.cshtml
@model List<Aluno>


<table class="table">
  <thead>
    <tr>
      <th scope="col">Matricula</th>
      <th scope="col">Nome</th>
      <th scope="col">CPF</th>
      <th scope="col">Idade</th>
    </tr>
  </thead>

  <thead>
  </thead>
  <tbody>
        @if (Model != null && Model.Any())
        {
            foreach (Aluno aluno in Model)
            {
                <tr>
                    <td>@aluno.Matricula</td>
                    <td>@aluno.Nome</td>
                    <td>@aluno.Cpf</td>
                    <td>@aluno.Idade</td>
                </tr>
            }           
        }
  </tbody>
</table>

<div class="text-center">
    <button class="btn-inserir">
        <a class="btn-inserir" type="button" asp-controller="Aluno" asp-action="AdicionarAluno">INSERIR ALUNO</a>
    </button>   
</div>

ProjetoJovemProgramadorMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Seja Bem vindo Lucas!</h1>
    <p>Learn about <a href="https://github.com/Messier104ngcc">Git Hub</a>.</p>
</div>

ProjetoJovemProgramadorMVC/Views/Login/Index.cshtml
@{
    ViewData["Title"] = "Login";
}

<form asp-controller="Login" asp-action="Logar" method="post">

    <label>Nome Usúario:</label>
    <input type="text" name="username"/>

    <label>Senha:</label>
    <input type="password" name="senha" />

    <input type="submit" value="Enviar"/>

</form>

ProjetoJovemProgramadorMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProjetoJovemProgramadorMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProjetoJovemProgramadorMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
         <nav class="nav"> 
            <div class="container-menu">
               <h1 class="display-5">Projeto Jovem Programador</h1>
               @*  @* <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation"> 
                    <span class="navbar-toggler-icon"></span>
                </button> *@
                <div class="menupage">
                    <ul class="menulink">
                        <button class="btn-home">
                            <a class="nav-link home" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </button>
                        <button class="btn-aluno">
                            <a class="nav-link aluno" asp-area="" asp-controller="Aluno" asp-action="Index" >Aluno</a>
                        </button>
                        <button class="btn-inicio">
                            <a class="nav-link pagina inicial" asp-area="" asp-controller="Pagina Inicial" asp-action="Privacy">Pagina Inicial</a>
                        </button>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container-footer">
            &copy; 2024 - ProjetoJovemProgramadorMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>